name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CosmosAzureVaultClientId:  ${{ secrets.CosmosAzureVaultClientId }}
      CosmosAzureVaultClientSecret: ${{ secrets.CosmosAzureVaultClientSecret }}
      CosmosAzureVaultUrl: ${{ secrets.CosmosAzureVaultUrl }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Cosmos.Akamai.sln
    - name: Build
      run: dotnet build ./Cosmos.Akamai.sln --no-restore
    - name: Test
      run: dotnet test ./CDT.Akamai.Tests/CDT.Akamai.Tests.csproj --no-build --verbosity normal
